package com.example.smartair.ui.onboarding;

import java.util.ArrayList;
import java.util.List;

public class OnboardingRepo {

    public static List<OnboardingScreen> getChildOnboardingScreens() {
        List<OnboardingScreen> screens = new ArrayList<>();
        screens.add(new OnboardingScreen("Welcome to SMART AIR! 🌟", "Hi! I'm here to help you understand asthma and use your inhalers the right way. Together, we'll track how you're feeling and learn to breathe easier!", "Let's Start!"));
        screens.add(new OnboardingScreen("Two Types of Medicine 💊", "You have two kinds of inhalers:\n\n🚑 Rescue Inhaler (Quick Relief)\n- Use when you suddenly feel bad\n- Helps you breathe better fast\n- Like a superhero that comes to help!\n\n🛡️ Controller Medicine (Daily Helper)\n- Use every day, even when you feel good\n- Keeps your airways calm and happy\n- Like a shield that protects you!", "Got it!"));
        screens.add(new OnboardingScreen("Your SMART AIR Tools 🎯", "Here's what you can do:\n- ✅ Log your medicines (so you remember!)\n- ✅ Check how you're feeling each day\n- ✅ Learn the best way to use your inhaler\n- ✅ Earn badges and streaks for doing great!\n- ✅ See your breathing zone (Green, Yellow, or Red)", "Cool!"));
        screens.add(new OnboardingScreen("Your Information is Safe 🔒", "What you should know:\n- Only YOU can see your own information\n- Your parent can see your logs to help you\n- Doctors can ONLY see what your parent chooses to share\n- Nothing is shared with doctors unless your parent says it's okay\n\nYou're in control of logging. Your parent is in control of sharing.", "I Understand"));
        screens.add(new OnboardingScreen("You're All Set! 🎉", "Remember:\n- Log your medicines every time\n- Tell us how you're feeling\n- Practice good inhaler technique\n- Have fun earning badges!\n\nIf you ever feel like you can't breathe well, tap the big red \"Having Trouble Breathing?\". We'll help you know what to do.", "Start Using SMART AIR"));
        return screens;
    }

    public static List<OnboardingScreen> getParentOnboardingScreens() {
        List<OnboardingScreen> screens = new ArrayList<>();
        screens.add(new OnboardingScreen("Welcome to SMART AIR", "SMART AIR helps your family manage asthma with confidence. Track medications, monitor symptoms, and share important information with your child's healthcare provider—all while maintaining complete control over your family's privacy.", "Get Started"));
        screens.add(new OnboardingScreen("Two Types of Asthma Medications", "🚑 Rescue Inhalers (Quick-Relief)\n- Albuterol, Levalbuterol, etc.\n- Used for sudden symptoms\n- Works quickly to open airways\n- Frequent use may signal poor control\n\n🛡️ Controller Medications (Long-term Control)\n- Inhaled corticosteroids, combination inhalers, etc.\n- Taken daily, even when feeling well\n- Reduces airway inflammation\n- Key to preventing symptoms\n\nWhy this matters: SMART AIR tracks both separately so you can see patterns and share accurate information with your provider.", "Continue"));
        screens.add(new OnboardingScreen("Your Asthma Management Hub", "📊 Monitor & Track\n- Medication logs (rescue & controller)\n- Daily symptom check-ins\n- Peak flow readings and zones\n- Trigger identification\n\n🔔 Stay Informed\n- Real-time alerts for concerning patterns\n- Low medication inventory warnings\n- Red zone notifications\n- Emergency triage guidance\n\n👨‍⚕️ Share with Providers\n- Generate comprehensive reports\n- Control exactly what's shared\n- Export data as PDF or CSV\n- Invite providers securely", "Next"));
        screens.add(new OnboardingScreen("Privacy First: Your Data, Your Control 🔒", "Default Privacy Settings:\n\n✅ Your child can only see their own data\n✅ You can view all your children's information\n✅ NOTHING is shared with healthcare providers by default\n✅ You decide what to share, when to share it\n\nHow it works:\n1. All data stays private within your family\n2. When ready, YOU choose exactly what to share\n3. You can turn sharing on/off anytime—instantly\n4. Providers can only see what you allow\n\nImportant: Even when you invite a provider, they see NOTHING until you turn on specific sharing toggles.", "I Understand"));
        screens.add(new OnboardingScreen("You Control Every Detail", "Share Only What You Want\n\nFor each child, you can individually share:\n\n- ☐ Rescue inhaler logs\n- ☐ Controller adherence summary\n- ☐ Symptoms & daily check-ins\n- ☐ Trigger information\n- ☐ Peak flow readings\n- ☐ Emergency triage incidents\n- ☐ Summary charts & visuals\n\nToggle sharing for each item independently.\n\nChanges take effect immediately and can be reversed anytime. Shared items will display a \"Shared with Provider\" tag so you always know what's visible.", "Got It"));
        screens.add(new OnboardingScreen("How to Invite Healthcare Providers", "Two Ways to Share Information:\n\nOption 1: In-App Access 🔗\n1. Generate a one-time invite code/link\n2. Send it to your provider (text, email, etc.)\n3. Code expires in 7 days\n4. You can revoke access anytime\n\nOption 2: Export Reports 📄\n- Generate PDF or CSV reports\n- Choose date range (3-6 months)\n- Email or print for appointments\n- No app access required for provider\n\nRemember: Even with an invite code, providers can only see data you've enabled in sharing controls.", "Clear"));
        screens.add(new OnboardingScreen("Emergency Guidance & Alerts", "SMART AIR Helps Keep Your Child Safe:\n\n🚨 Emergency Triage\n- One-tap \"Having Trouble Breathing?\". button\n- Checks for critical warning signs\n- Provides clear next steps (call 911 or home treatment)\n- Alerts you immediately when used\n\n🔔 Smart Alerts (you'll receive notifications for):\n- Red zone days\n- Frequent rescue use (3+ times in 3 hours)\n- \"Worse after dose\" reports\n- Low or expired medication\n- Triage escalations\n\nImportant: This app provides guidance, not medical diagnosis. Always call emergency services if you're concerned.", "Understood"));
        screens.add(new OnboardingScreen("You're Ready to Start!", "Next Steps:\n1. ✅ Add your child's profile\n2. ✅ Set their Personal Best peak flow (from asthma action plan)\n3. ✅ Configure medication schedule\n4. ✅ Start logging!\n\nNeed Help?\n- Tap the ? icon anytime for guidance\n- Visit Settings to adjust alert preferences\n- Review privacy controls under Sharing\n\nYour family's asthma data stays private until you decide to share it.", "Add My Child / Start"));
        return screens;
    }

    public static List<OnboardingScreen> getProviderOnboardingScreens() {
        List<OnboardingScreen> screens = new ArrayList<>();
        screens.add(new OnboardingScreen("Welcome, Healthcare Provider", "SMART AIR gives you read-only access to parent-authorized patient asthma data. Parents maintain complete control over what you can view and can modify sharing permissions at any time.", "Continue"));
        screens.add(new OnboardingScreen("Understanding Your Access", "What You Can Do:\n- ✅ View patient summaries shared by parents\n- ✅ See medication logs (if authorized)\n- ✅ Review symptom patterns and triggers\n- ✅ Access peak flow data and zone history\n- ✅ View emergency triage incidents\n- ✅ Export data for clinical records\n\nWhat You Cannot Do:\n- ❌ Edit or add any patient data\n- ❌ Change patient settings\n- ❌ Contact patients through the app\n- ❌ View data parents haven't authorized", "Understood"));
        screens.add(new OnboardingScreen("Parent-Controlled Data Sharing", "The Parent Decides Everything:\n\n1. Invite Process: Parents generate a one-time invite code/link for you\n2. Granular Control: Parents choose exactly what data categories to share per child\n3. Real-Time Changes: Parents can turn sharing on/off instantly—you'll see changes immediately\n4. Revocable Access: Parents can revoke your access anytime\n\nWhat You'll See:\n- Only data for children whose parents have invited you\n- Only data categories the parent has enabled\n- A clear indicator showing what's currently shared\n\nYou may see different information for different patients based on their parents' preferences.", "Clear"));
        screens.add(new OnboardingScreen("Privacy & Professional Responsibility", "Important Reminders:\n\n🔒 All patient data is PHI (Protected Health Information)\n- Handle according to HIPAA and professional standards\n- Do not share access credentials\n- Only access patient data for legitimate clinical purposes\n\n⚠️ This is supplemental information\n- SMART AIR data supports, but doesn't replace, clinical assessment\n- Verify critical information with patients/parents directly\n- Emergency guidance in app is not a substitute for professional judgment\n\n📋 No Diagnostic Claims\n- App provides monitoring and tracking only\n- All clinical decisions remain your responsibility", "I Agree"));
        screens.add(new OnboardingScreen("Available Data Categories", "Parents can share the following per child:\n\n📋 Medication Data\n- Rescue inhaler use (frequency, timing)\n- Controller medication adherence\n\n🤒 Symptoms & Triggers\n- Daily symptom check-ins\n- Identified asthma triggers\n- Activity limitations, night waking\n\n📊 Peak Flow & Zones\n- PEF readings over time\n- Zone distribution (Green/Yellow/Red)\n- Personal Best baseline\n\n🚨 Safety Events\n- Emergency triage incidents\n- Warning signs checked\n- Actions taken\n\n📈 Summary Reports\n- Time-series charts\n- Adherence statistics\n- Exportable PDF/CSV formats", "Next"));
        screens.add(new OnboardingScreen("How to View Patient Information", "To Access a Patient's Data:\n\n1. Receive Invite: Parent sends you a code/link (valid 7 days)\n2. Enter Code: Use it to link the patient to your account\n3. View Dashboard: Access the patient's shared information\n4. Review Reports: Generate summaries for clinical use\n\nIf you don't see expected data:\n- The parent may not have enabled sharing for that category\n- Suggest the parent check their sharing settings\n- Parents can also export and send reports directly\n\nRemember: Invite codes expire in 7 days. Ask parents to regenerate if needed.", "Got It"));
        screens.add(new OnboardingScreen("You're All Set", "Getting Started:\n\n🔑 Enter Your First Invite Code\nTap \"Add Patient\" and enter the code provided by a parent\n\n📧 Or Wait for an Invite\nParents will send you invite links when they're ready to share\n\n💬 Communicate with Families\nRemind parents they can:\n- Adjust sharing settings anytime\n- Export reports for appointments\n- Use SMART AIR data to inform care discussions\n\nNeed help? Contact support at support@smartairapp.com", "Go to Dashboard"));
        return screens;
    }
}

class OnboardingScreen {
    String title;
    String content;
    String buttonText;

    public OnboardingScreen(String title, String content, String buttonText) {
        this.title = title;
        this.content = content;
        this.buttonText = buttonText;
    }
}